USE [master]
GO

/****** Object:  Database [UsersDB]    Script Date: 10/11/2013 16:55:39 ******/
CREATE DATABASE [UsersDB]  

GO

ALTER DATABASE [UsersDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UsersDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsersDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersDB] SET  READ_WRITE 
GO

ALTER DATABASE [UsersDB] SET RECOVERY FULL 
GO

ALTER DATABASE [UsersDB] SET  MULTI_USER 
GO

ALTER DATABASE [UsersDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersDB] SET DB_CHAINING OFF 
GO

USE [UsersDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Username] [nvarchar](30) NOT NULL,
	[Password] [nvarchar](200) NOT NULL
) ON [PRIMARY]

GO



